functionsDirectory = "C:\\Users\\Bandi\\Main\\All things Crafted\\GitHub\\crafted-gamz\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\Bandi\\Main\\All things Crafted\\GitHub\\crafted-gamz"
publishOrigin = "config"
base = "C:\\Users\\Bandi\\Main\\All things Crafted\\GitHub\\crafted-gamz"
functions = "C:\\Users\\Bandi\\Main\\All things Crafted\\GitHub\\crafted-gamz\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/value.json"
to = "/.netlify/functions/value"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]