exports.handler = async function(event, context) {
  const values = [
    "1",
    "10 Minutes Till Dawn",
    "1V1 Lol",
    "1V1 Space",
    "2048 Multitask",
    "2048",
    "99 Balls",
    "A Dance Of Fire And Ice",
    "Achievement Unlocked",
    "A Dark Room",
    "Adrenaline Challenge",
    "Adventure Drivers",
    "Amazing Rope Police",
    "Among Us",
    "Awesome Tanks 2",
    "Backrooms",
    "Backrooms 2D",
    "Bacon May Die",
    "Bad Ice Cream 2",
    "Bad Ice Cream 3",
    "Bad Ice Cream",
    "Baldis Basics",
    "Basket Random",
    "Basketball Stars",
    "Basketbros IO",
    "Battle For Gondor",
    "Bitlife",
    "Block Post",
    "Bloons TD",
    "Bloons TD 2",
    "Big Neon Tower, Tiny Square",
    "Bonk.io",
    "Btd 4",
    "Btd 5",
    "Bing Tower Tiny Square",
    "Bus And Subway",
    "Champion Island",
    "Chess",
    "Chill Radio",
    "Cluster Rush",
    "Cmm Client (Minecraft)",
    "Cut The Rope Holiday",
    "Cut The Rope 2",
    "Cut The Rope",
    "Death Run 3D",
    "Deepest Sword",
    "Doge Miner 2",
    "Doom",
    "Drift Boss",
    "Drift Hunters",
    "Drive Mad",
    "Duck Life 2",
    "Duck Life 3",
    "Duck Life 4",
    "Dumb Ways To Die",
    "Earntodie",
    "Edge Surf",
    "Fancy Pants Adventures",
    "Fireboy And Watergirl Forest Temple",
    "Flappy Bird",
    "Flappy Bird",
    "Flappy Plane",
    "Fleeing The Complex",
    "Friday Night Funkin",
    "Fruit Ninja",
    "Gdtd",
    "Getaway Shootout",
    "Google Snake",
    "Happy Wheels",
    "Hba",
    "Hill Climb Racing",
    "Hungry Lamu",
    "Idle Breakout",
    "Idle Shark",
    "Impossible Quiz",
    "Impossible Quiz 2",
    "Iron Dash",
    "Just One Boss",
    "Kirka.io",
    "Knife Master",
    "Learn To Fly 2",
    "Ltf3",
    "Madalin Stunt Cars 2",
    "Madalin Stunt Cars 3",
    "Mario",
    "Marvin Spectrum",
    "Minecraft 15",
    "Minecraft 18",
    "Minecraft Classic",
    "Minecraft Beta",
    "Minecraft Tower Defence",
    "Minesweeper",
    "Miniputt",
    "Missiles",
    "Monster Tracks",
    "Motox 3M Pool Party",
    "Motox 3M Spooky Edition",
    "Motox 3M Winter Edition",
    "Motox 3M",
    "Motox 3M 2",
    "Neal.Fun",
    "Overwatch",
    "Pandemic 2",
    "Retro Bowl",
    "Rhythm Doctor",
    "Roblox",
    "Rooftop Snipers",
    "Ruffle (Launcher)",
    "Rocket League",
    "Run 2",
    "Run 3",
    "Run",
    "Run 2",
    "Run 3",
    "Run 4 Bootleg",
    "Runner",
    "Sand Game",
    "Sandboxels",
    "Santy Is Home",
    "Scooperia",
    "Scrapmetal",
    "Scratcharia",
    "Shape Shootout",
    "Stickman Survival",
    "Shell Shockers",
    "Shogun Showdown",
    "Shot In The Dark",
    "Shuttledeck",
    "Sky Car Stunt",
    "Sleeping Beauty",
    "Slime Rush TD",
    "Slither.io",
    "Slope 2",
    "Slope Ball",
    "Slope",
    "Sm64",
    "Smash Karts",
    "Smoking Barrels",
    "Snowbattle",
    "Snowrider3d",
    "Soccer Random",
    "Soccer Skills",
    "Soldier Legend",
    "Solitaire",
    "Sort The Court",
    "Soundboard",
    "Space Company",
    "Space Garden",
    "Spelunky",
    "Spinningrat",
    "Squaredash",
    "Ssurferbotleg",
    "Stack Bump 3d",
    "Stack",
    "Starblast",
    "Starblastio",
    "Starblastx",
    "Starve.io",
    "Steak And Shake",
    "Steal",
    "Stick Figure Penalty",
    "Stickman",
    "Stickman Dirtbike",
    "Stickman Parkour",
    "Stickman Wars",
    "Stickwar",
    "Stickwars2",
    "Stickwars3",
    "Sticksoccer",
    "Stun Run",
    "Stun Run2",
    "Stuntcar",
    "Stuntracer",
    "Super Mario 64",
    "Supermegamonster",
    "Super Mario",
    "Supermariobros",
    "Super Mario World",
    "Surviv.io",
    "Surviv.io",
    "Surfers",
    "Sword And Shield",
    "Swords And Sandals",
    "Swordsandsandals",
    "Swordsandsandals2",
    "Swordsandsandals3",
    "Swordsandsandals4",
    "Swordsandsandals5",
    "Swordsandsandals6",
    "Swordsandsandals7",
    "Swordsandsandals8",
    "Swordsandsandals9",
    "Swordsandsandals10"
  ];

  const now = new Date();
  const month = now.getMonth();
  const year = now.getFullYear();
  const seed = year * 100 + month;
  const index = seed % values.length;
  const chosen = values[index];

  return {
    statusCode: 200,
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600"
    },
    body: JSON.stringify({ value: chosen })
  };
};
