const gameConfigs = {
  "cmm-client": { title: "Cmm Client", url: "cmm-client" },
  "doomori": { title: "Doomori", url: "doomori" },
  "dogeminer": { title: "Dogeminer", url: "dogeminer" },
  "dogeminer2": { title: "Dogeminer2", url: "dogeminer2" },
  "hexgl": { title: "Hexgl", url: "hexgl" },
  "monkeymart": { title: "Monkeymart", url: "monkeymart" },
  "offlineparadise": { title: "Offlineparadise", url: "offlineparadise" },
  "rocket-league": { title: "Rocket League", url: "rocket-league" },
  "run-2": { title: "Run 2", url: "run-2" },
  "shapeshootout": { title: "Shape Shootout", url: "shapeshootout" },
  "stickman-survival": { title: "Stickman Survival", url: "stickman-survival" },
  "Trimps": { title: "Trimps", url: "Trimps" },
  "a-dance-of-fire-and-ice": { title: "A Dance Of Fire And Ice", url: "a-dance-of-fire-and-ice" },
  "achievementunlocked": { title: "Achievementunlocked", url: "achievementunlocked" },
  "adarkroom": { title: "Adarkroom", url: "adarkroom" },
  "adrenalinechallenge": { title: "Adrenalinechallenge", url: "adrenalinechallenge" },
  "adventure-drivers": { title: "Adventure Drivers", url: "adventure-drivers" },
  "ages-of-conflict": { title: "Ages Of Conflict", url: "ages-of-conflict" },
  "alienhominid": { title: "Alienhominid", url: "alienhominid" },
  "amazing-rope-police": { title: "Amazing Rope Police", url: "amazing-rope-police" },
  "amidst-the-clouds": { title: "Amidst The Clouds", url: "amidst-the-clouds" },
  "among-us": { title: "Among Us", url: "among-us" },
  "angry-sharks": { title: "Angry Sharks", url: "angry-sharks" },
  "aquapark-slides": { title: "Aquapark Slides", url: "aquapark-slides" },
  "astray": { title: "Astray", url: "astray" },
  "avalanche": { title: "Avalanche", url: "avalanche" },
  "awesometanks2": { title: "Awesometanks2", url: "awesometanks2" },
  "backrooms": { title: "Backrooms", url: "backrooms" },
  "backrooms-2d": { title: "Backrooms 2d", url: "backrooms-2d" },
  "backrooms2d": { title: "Backrooms2d", url: "backrooms2d" },
  "bacon-may-die": { title: "Bacon May Die", url: "bacon-may-die" },
  "bad-ice-cream": { title: "Bad Ice Cream", url: "bad-ice-cream" },
  "bad-ice-cream-2": { title: "Bad Ice Cream 2", url: "bad-ice-cream-2" },
  "bad-ice-cream-3": { title: "Bad Ice Cream 3", url: "bad-ice-cream-3" },
  "baldis-basics": { title: "Baldis Basics", url: "baldis-basics" },
  "balldodge": { title: "Balldodge", url: "balldodge" },
  "ballistic-chickens": { title: "Ballistic Chickens", url: "ballistic-chickens" },
  "basket-random": { title: "Basket Random", url: "basket-random" },
  "basketball-stars": { title: "Basketball Stars", url: "basketball-stars" },
  "basketbros-io": { title: "Basketbros Io", url: "basketbros-io" },
  "battleforgondor": { title: "Battleforgondor", url: "battleforgondor" },
  "bigredbutton": { title: "Bigredbutton", url: "bigredbutton" },
  "bitlife": { title: "Bitlife", url: "bitlife" },
  "blacholesquare": { title: "Blacholesquare", url: "blacholesquare" },
  "blackknight": { title: "Blackknight", url: "blackknight" },
  "blockpost": { title: "Blockpost", url: "blockpost" },
  "bloonstd": { title: "Bloonstd", url: "bloonstd" },
  "bloonstd2": { title: "Bloonstd2", url: "bloonstd2" },
  "bloxors": { title: "Bloxors", url: "bloxors" },
  "bntts": { title: "Bntts", url: "bntts" },
  "bobtherobber2": { title: "Bobtherobber2", url: "bobtherobber2" },
  "bonkio": { title: "Bonkio", url: "bonkio" },
  "boxhead2play": { title: "Boxhead2play", url: "boxhead2play" },
  "boxing-random": { title: "Boxing Random", url: "boxing-random" },
  "breakingthebank": { title: "Breakingthebank", url: "breakingthebank" },
  "btd4": { title: "Bloons TD 4", url: "btd4" },
  "btd5": { title: "Bloons TD 5", url: "btd5" },
  "btts": { title: "Btts", url: "btts" },
  "burger-and-frights": { title: "Burger And Frights", url: "burger-and-frights" },
  "bus-and-subway": { title: "Bus And Subway", url: "bus-and-subway" },
  "busandsubway": { title: "Busandsubway", url: "busandsubway" },
  "cannon-basketball-4": { title: "Cannon Basketball 4", url: "cannon-basketball-4" },
  "canyondefense": { title: "Canyondefense", url: "canyondefense" },
  "cars-simulator": { title: "Cars Simulator", url: "cars-simulator" },
  "cell-machine": { title: "Cell Machine", url: "cell-machine" },
  "champion-island": { title: "Champion Island", url: "champion-island" },
  "championarcher": { title: "Championarcher", url: "championarcher" },
  "checkers": { title: "Checkers", url: "checkers" },
  "chess": { title: "Chess", url: "chess" },
  "chill-radio": { title: "Chill Radio", url: "chill-radio" },
  "chrome-dino": { title: "Chrome Dino", url: "chrome-dino" },
  "circlo": { title: "Circlo", url: "circlo" },
  "classicube": { title: "Classicube", url: "classicube" },
  "cluster-rush": { title: "Cluster Rush", url: "cluster-rush" },
  "cnpingpong": { title: "Cnpingpong", url: "cnpingpong" },
  "connect3": { title: "Connect3", url: "connect3" },
  "cookie-clickers/cookie-clicker": { title: "Cookie Clickers Cookie Clicker", url: "cookie-clickers/cookie-clicker" },
  "core-ball": { title: "Core Ball", url: "core-ball" },
  "craftmine": { title: "Craftmine", url: "craftmine" },
  "creativekillchamber": { title: "Creativekillchamber", url: "creativekillchamber" },
  "crossyroad": { title: "Crossyroad", url: "crossyroad" },
  "csgo-clicker": { title: "CSGO Clicker", url: "csgo-clicker" },
  "ctr": { title: "Ctr", url: "ctr" },
  "ctr-holiday": { title: "CTR Holiday", url: "ctr-holiday" },
  "ctr-tr": { title: "CTR TR", url: "ctr-tr" },
  "cubefield": { title: "Cubefield", url: "cubefield" },
  "cupcake2048": { title: "Cupcake2048", url: "cupcake2048" },
  "dante": { title: "Dante", url: "dante" },
  "deal-or-no-deal": { title: "Deal Or No Deal", url: "deal-or-no-deal" },
  "death-run-3d": { title: "Death Run 3d", url: "death-run-3d" },
  "deepest-sword": { title: "Deepest Sword", url: "deepest-sword" },
  "defend-the-tank": { title: "Defend The Tank", url: "defend-the-tank" },
  "doctor-acorn2": { title: "Doctor Acorn2", url: "doctor-acorn2" },
  "dodge": { title: "Dodge", url: "dodge" },
  "doge2048": { title: "Doge2048", url: "doge2048" },
  "doodle-jump": { title: "Doodle Jump", url: "doodle-jump" },
  "doom": { title: "Doom", url: "doom" },
  "doublewires": { title: "Doublewires", url: "doublewires" },
  "dragon-vs-bricks": { title: "Dragon Vs Bricks", url: "dragon-vs-bricks" },
  "draw-the-hill": { title: "Draw The Hill", url: "draw-the-hill" },
  "drift-boss": { title: "Drift Boss", url: "drift-boss" },
  "drift-hunters": { title: "Drift Hunters", url: "drift-hunters" },
  "drive-mad": { title: "Drive Mad", url: "drive-mad" },
  "dsc": { title: "Dsc", url: "dsc" },
  "ducklife1": { title: "Duck Life 1", url: "ducklife1" },
  "ducklife2": { title: "Duck Life 2", url: "ducklife2" },
  "ducklife3": { title: "Duck Life 3", url: "ducklife3" },
  "ducklife4": { title: "Duck Life 4", url: "ducklife4" },
  "duke-nukem-2": { title: "Duke Nukem 2", url: "duke-nukem-2" },
  "dumbwaystodie": { title: "Dumbwaystodie", url: "dumbwaystodie" },
  "eaglerfaithful": { title: "Eaglerfaithful", url: "eaglerfaithful" },
  "earntodie": { title: "Earntodie", url: "earntodie" },
  "edge-surf": { title: "Edge Surf", url: "edge-surf" },
  "edgenotfound": { title: "Edgenotfound", url: "edgenotfound" },
  "eel-slap": { title: "Eel Slap", url: "eel-slap" },
  "eggycar": { title: "Eggycar", url: "eggycar" },
  "elasticman": { title: "Elasticman", url: "elasticman" },
  "endlesswar3": { title: "Endlesswar3", url: "endlesswar3" },
  "escapingtheprison": { title: "Escapingtheprison", url: "escapingtheprison" },
  "evil-glitch": { title: "Evil Glitch", url: "evil-glitch" },
  "evolution": { title: "Evolution", url: "evolution" },
  "exo": { title: "Exo", url: "exo" },
  "factoryballs": { title: "Factoryballs", url: "factoryballs" },
  "fairsquares": { title: "Fairsquares", url: "fairsquares" },
  "fake-virus": { title: "Fake Virus", url: "fake-virus" },
  "fancypantsadventures": { title: "Fancypantsadventures", url: "fancypantsadventures" },
  "fantasy-dash": { title: "Fantasy Dash", url: "fantasy-dash" },
  "fireboywatergirlforesttemple": { title: "Fireboy Watergirl Forest Temple", url: "fireboywatergirlforesttemple" },
  "flappy-2048": { title: "Flappy 2048", url: "flappy-2048" },
  "flappy-bird": { title: "Flappy Bird", url: "flappy-bird" },
  "flappy-plane": { title: "Flappy Plane", url: "flappy-plane" },
  "flappybird": { title: "Flappybird", url: "flappybird" },
  "flappyplane": { title: "Flappyplane", url: "flappyplane" },
  "flashtetris": { title: "Flashtetris", url: "flashtetris" },
  "fleeingthecomplex": { title: "Fleeingthecomplex", url: "fleeingthecomplex" },
  "flippy-fish": { title: "Flippy Fish", url: "flippy-fish" },
  "fnaw": { title: "Fnaw", url: "fnaw" },
  "fridaynightfunkin": { title: "Fridaynightfunkin", url: "fridaynightfunkin" },
  "froggys-battle": { title: "Froggys Battle", url: "froggys-battle" },
  "fruitninja": { title: "Fruitninja", url: "fruitninja" },
  "frying-nemo": { title: "Frying Nemo", url: "frying-nemo" },
  "gachalife": { title: "Gachalife", url: "gachalife" },
  "game-inside": { title: "Game Inside", url: "game-inside" },
  "gdtd": { title: "Gdtd", url: "gdtd" },
  "gearsofbabies": { title: "Gearsofbabies", url: "gearsofbabies" },
  "generic-fishing-game": { title: "Generic Fishing Game", url: "generic-fishing-game" },
  "gachalife": { title: "Gachalife", url: "gachalife" },
  "geodash": { title: "Geodash", url: "geodash" },
  "geodashlite": { title: "Geodashlite", url: "geodashlite" },
  "geogeo": { title: "Geogeo", url: "geogeo" },
  "geops1": { title: "Geops1", url: "geops1" },
  "georash": { title: "Georash", url: "georash" },
  "georgeandtheprinter": { title: "Georgeandtheprinter", url: "georgeandtheprinter" },
  "geotrash": { title: "Geotrash", url: "geotrash" },
  "getaway-shootout": { title: "Getaway Shootout", url: "getaway-shootout" },
  "gimme-the-airpod": { title: "Gimme The Airpod", url: "gimme-the-airpod" },
  "glass-city": { title: "Glass City", url: "glass-city" },
  "gmonster": { title: "Gmonster", url: "gmonster" },
  "go-ball": { title: "Go Ball", url: "go-ball" },
  "goodnight": { title: "Goodnight", url: "goodnight" },
  "goodnight-meowmie": { title: "Goodnight Meowmie", url: "goodnight-meowmie" },
  "google-feud": { title: "Google Feud", url: "google-feud" },
  "google-snake": { title: "Google Snake", url: "google-snake" },
  "gravity-soccer": { title: "Gravity Soccer", url: "gravity-soccer" },
  "greybox": { title: "Greybox", url: "greybox" },
  "grindcraft": { title: "Grindcraft", url: "grindcraft" },
  "hackertype": { title: "Hackertype", url: "hackertype" },
  "handshakes": { title: "Handshakes", url: "handshakes" },
  "happy-hop": { title: "Happy Hop", url: "happy-hop" },
  "happywheels": { title: "Happywheels", url: "happywheels" },
  "hardware-tycoon": { title: "Hardware Tycoon", url: "hardware-tycoon" },
  "hba": { title: "Hba", url: "hba" },
  "helicopter": { title: "Helicopter", url: "helicopter" },
  "hellscaper": { title: "Hellscaper", url: "hellscaper" },
  "hexempire": { title: "Hexempire", url: "hexempire" },
  "hextris": { title: "Hextris", url: "hextris" },
  "highrisehop": { title: "Highrisehop", url: "highrisehop" },
  "hill-climb-racing": { title: "Hill Climb Racing", url: "hill-climb-racing" },
  "hungry-lamu": { title: "Hungry Lamu", url: "hungry-lamu" },
  "iceagebaby": { title: "Iceagebaby", url: "iceagebaby" },
  "iceagebaby2": { title: "Iceagebaby2", url: "iceagebaby2" },
  "idle-breakout": { title: "Idle Breakout", url: "idle-breakout" },
  "idle-shark": { title: "Idle Shark", url: "idle-shark" },
  "idledice": { title: "Idledice", url: "idledice" },
  "impossiblequiz": { title: "Impossiblequiz", url: "impossiblequiz" },
  "impossiblequiz2": { title: "Impossiblequiz2", url: "impossiblequiz2" },
  "impossiblequizbeta": { title: "Impossiblequizbeta", url: "impossiblequizbeta" },
  "interactivebuddy": { title: "Interactivebuddy", url: "interactivebuddy" },
  "invite-the-blackbird": { title: "Invite The Blackbird", url: "invite-the-blackbird" },
  "iron-dash": { title: "Iron Dash", url: "iron-dash" },
  "irondash": { title: "Irondash", url: "irondash" },
  "jetpack-joyride": { title: "Jetpack Joyride", url: "jetpack-joyride" },
  "just-fall": { title: "Just Fall", url: "just-fall" },
  "just-one-boss": { title: "Just One Boss", url: "just-one-boss" },
  "kirkaio": { title: "Kirkaio", url: "kirkaio" },
  "kitchen-gun-game": { title: "Kitchen Gun Game", url: "kitchen-gun-game" },
  "kittencannon": { title: "Kittencannon", url: "kittencannon" },
  "knife-master": { title: "Knife Master", url: "knife-master" },
  "krunker": { title: "Krunker", url: "krunker" },
  "learntofly": { title: "Learntofly", url: "learntofly" },
  "learntofly2": { title: "Learntofly2", url: "learntofly2" },
  "level13": { title: "Level13", url: "level13" },
  "linerider": { title: "Linerider", url: "linerider" },
  "linkgen": { title: "Linkgen", url: "linkgen" },
  "ltf-idle": { title: "Ltf Idle", url: "ltf-idle" },
  "ltf3": { title: "Ltf3", url: "ltf3" },
  "madalin-stunt-cars-2": { title: "Madalin Stunt Cars 2", url: "madalin-stunt-cars-2" },
  "madalin-stunt-cars-3": { title: "Madalin Stunt Cars 3", url: "madalin-stunt-cars-3" },
  "mario": { title: "Mario", url: "mario" },
  "marvinspectrum": { title: "Marvinspectrum", url: "marvinspectrum" },
  "matrixrampage": { title: "Matrixrampage", url: "matrixrampage" },
  "mcje": { title: "Mcje", url: "mcje" },
  "meme2048": { title: "Meme2048", url: "meme2048" },
  "merge-round-racers": { title: "Merge Round Racers", url: "merge-round-racers" },
  "mindustry": { title: "Mindustry", url: "mindustry" },
  "mineblocks": { title: "Mineblocks", url: "mineblocks" },
  "minecraft-15": { title: "Minecraft 1.5", url: "minecraft-15" },
  "minecraft-18": { title: "Minecraft 1.8", url: "minecraft-18" },
  "minecraft-classic": { title: "Minecraft Classic", url: "minecraft-classic" },
  "minecraftbeta": { title: "Minecraft Beta", url: "minecraftbeta" },
  "minecrafttowerdefence": { title: "Minecraft Tower Defence", url: "minecrafttowerdefence" },
  "minesweeper": { title: "Minesweeper", url: "minesweeper" },
  "miniputt": { title: "Miniputt", url: "miniputt" },
  "missiles": { title: "Missiles", url: "missiles" },
  "monster-tracks": { title: "Monster Tracks", url: "monster-tracks" },
  "motox3m": { title: "Motox3m", url: "motox3m" },
  "motox3m-pool": { title: "Motox3m Pool", url: "motox3m-pool" },
  "motox3m-spooky": { title: "Motox3m Spooky", url: "motox3m-spooky" },
  "motox3m-winter": { title: "Motox3m Winter", url: "motox3m-winter" },
  "motox3m2": { title: "Motox3m2", url: "motox3m2" },
  "my-rusty-submarine": { title: "My Rusty Submarine", url: "my-rusty-submarine" },
  "n-gon": { title: "N Gon", url: "n-gon" },
  "neal.fun": { title: "Neal.fun", url: "neal.fun" },
  "ninja": { title: "Ninja", url: "ninja" },
  "ninjavsevilcorp": { title: "Ninja VS Evil Corp", url: "ninjavsevilcorp" },
  "noob-steve-parkour": { title: "Noob Steve Parkour", url: "noob-steve-parkour" },
  "ns-shaft": { title: "Ns Shaft", url: "ns-shaft" },
  "nsresurgence": { title: "Nsresurgence", url: "nsresurgence" },
  "om-bounce": { title: "Om Bounce", url: "om-bounce" },
  "osu!": { title: "Osu!", url: "osu!" },
  "out-of-ctrl": { title: "Out Of Ctrl", url: "out-of-ctrl" },
  "overwatch": { title: "Overwatch", url: "overwatch" },
  "ovo": { title: "Ovo", url: "ovo" },
  "pandemic2": { title: "Pandemic2", url: "pandemic2" },
  "papasburgeria": { title: "Papas Burgeria", url: "papasburgeria" },
  "papaspizzaria": { title: "Papas Pizzaria", url: "papaspizzaria" },
  "paperio2": { title: "Paper.io 2", url: "paperio2" },
  "papery-planes": { title: "Papery Planes", url: "papery-planes" },
  "particle-clicker": { title: "Particle Clicker", url: "particle-clicker" },
  "piclient": { title: "Piclient", url: "piclient" },
  "pigeon-ascent": { title: "Pigeon Ascent", url: "pigeon-ascent" },
  "pixel-gun-survival": { title: "Pixel Gun Survival", url: "pixel-gun-survival" },
  "planetlife": { title: "Planetlife", url: "planetlife" },
  "plantsvzombie1": { title: "Plantsvzombie1", url: "plantsvzombie1" },
  "polybranch": { title: "Polybranch", url: "polybranch" },
  "popcat-classic": { title: "Popcat Classic", url: "popcat-classic" },
  "portalflash": { title: "Portalflash", url: "portalflash" },
  "precision-client": { title: "Precision Client", url: "precision-client" },
  "protektor": { title: "Protektor", url: "protektor" },
  "push-the-square": { title: "Push The Square", url: "push-the-square" },
  "push-your-luck": { title: "Push Your Luck", url: "push-your-luck" },
  "rabbit-samurai": { title: "Rabbit Samurai", url: "rabbit-samurai" },
  "rabbit-samurai2": { title: "Rabbit Samurai2", url: "rabbit-samurai2" },
  "resent-client": { title: "Resent Client", url: "resent-client" },
  "retro-bowl": { title: "Retro Bowl", url: "retro-bowl" },
  "rhythm-doctor": { title: "Rhythm Doctor", url: "rhythm-doctor" },
  "riddleschool": { title: "Riddleschool", url: "riddleschool" },
  "riddleschool2": { title: "Riddleschool2", url: "riddleschool2" },
  "riddleschool3": { title: "Riddleschool3", url: "riddleschool3" },
  "riddleschool4": { title: "Riddleschool4", url: "riddleschool4" },
  "riddleschool5": { title: "Riddleschool5", url: "riddleschool5" },
  "riddletransfer": { title: "Riddletransfer", url: "riddletransfer" },
  "riddletransfer2": { title: "Riddletransfer2", url: "riddletransfer2" },
  "roblox": { title: "Roblox", url: "roblox" },
  "roblox-copy": { title: "Roblox Copy", url: "roblox-copy" },
  "robuxclicker": { title: "Robuxclicker", url: "robuxclicker" },
  "rolling-forests": { title: "Rolling Forests", url: "rolling-forests" },
  "rolly-vortex": { title: "Rolly Vortex", url: "rolly-vortex" },
  "rooftop-snipers": { title: "Rooftop Snipers", url: "rooftop-snipers" },
  "roommate": { title: "Roommate", url: "roommate" },
  "ruffle": { title: "Ruffle", url: "ruffle" },
  "run": { title: "Run", url: "run" },
  "run-3": { title: "Run 3", url: "run-3" },
  "run2": { title: "Run 2", url: "run2" },
  "run3": { title: "Run 3", url: "run3" },
  "run4bootleg": { title: "Run4bootleg", url: "run4bootleg" },
  "runner": { title: "Runner", url: "runner" },
  "sand-game": { title: "Sand Game", url: "sand-game" },
  "sandboxels": { title: "Sandboxels", url: "sandboxels" },
  "santy-is-home": { title: "Santy Is Home", url: "santy-is-home" },
  "scooperia": { title: "Scooperia", url: "scooperia" },
  "scrapmetal": { title: "Scrapmetal", url: "scrapmetal" },
  "scratcharia": { title: "Scratcharia", url: "scratcharia" },
  "shellshockers": { title: "Shellshockers", url: "shellshockers" },
  "shogunshowdown": { title: "Shogunshowdown", url: "shogunshowdown" },
  "shotinthedark": { title: "Shotinthedark", url: "shotinthedark" },
  "shuttledeck": { title: "Shuttledeck", url: "shuttledeck" },
  "sky-car-stunt": { title: "Sky Car Stunt", url: "sky-car-stunt" },
  "sleepingbeauty": { title: "Sleepingbeauty", url: "sleepingbeauty" },
  "slime-rush-td": { title: "Slime Rush Td", url: "slime-rush-td" },
  "slitherio": { title: "Slitherio", url: "slitherio" },
  "slope": { title: "Slope", url: "slope" },
  "slope-2": { title: "Slope 2", url: "slope-2" },
  "slope-ball": { title: "Slope Ball", url: "slope-ball" },
  "sm64": { title: "Sm64", url: "sm64" },
  "smashkarts": { title: "Smashkarts", url: "smashkarts" },
  "smokingbarrels": { title: "Smokingbarrels", url: "smokingbarrels" },
  "snowbattle": { title: "Snowbattle", url: "snowbattle" },
  "snowrider3d": { title: "Snowrider3d", url: "snowrider3d" },
  "soccer-random": { title: "Soccer Random", url: "soccer-random" },
  "soccer-skills": { title: "Soccer Skills", url: "soccer-skills" },
  "soldier-legend": { title: "Soldier Legend", url: "soldier-legend" },
  "solitaire": { title: "Solitaire", url: "solitaire" },
  "sort-the-court": { title: "Sort The Court", url: "sort-the-court" },
  "soundboard": { title: "Soundboard", url: "soundboard" },
  "space-company": { title: "Space Company", url: "space-company" },
  "spacegarden": { title: "Spacegarden", url: "spacegarden" },
  "spelunky": { title: "Spelunky", url: "spelunky" },
  "spinningrat": { title: "Spinningrat", url: "spinningrat" },
  "squaredash": { title: "Squaredash", url: "squaredash" },
  "ssurferbotleg": { title: "Ssurferbotleg", url: "ssurferbotleg" },
  "stack": { title: "Stack", url: "stack" },
  "stack-bump-3d": { title: "Stack Bump 3d", url: "stack-bump-3d" },
  "starve": { title: "Starve", url: "starve" },
  "station-141": { title: "Station 141", url: "station-141" },
  "stationmeltdown": { title: "Stationmeltdown", url: "stationmeltdown" },
  "stealingthediamond": { title: "Stealingthediamond", url: "stealingthediamond" },
  "stick-archers": { title: "Stick Archers", url: "stick-archers" },
  "stick-duel-battle": { title: "Stick Duel Battle", url: "stick-duel-battle" },
  "stick-merge": { title: "Stick Merge", url: "stick-merge" },
  "stickman-boost": { title: "Stickman Boost", url: "stickman-boost" },
  "stickman-golf": { title: "Stickman Golf", url: "stickman-golf" },
  "stickman-hook": { title: "Stickman Hook", url: "stickman-hook" },
  "stickwar": { title: "Stickwar", url: "stickwar" },
  "stormthehouse2": { title: "Stormthehouse2", url: "stormthehouse2" },
  "stumble-guys": { title: "Stumble Guys", url: "stumble-guys" },
  "subway-surfers": { title: "Subway Surfers", url: "subway-surfers" },
  "subway-surfers-ny": { title: "Subway Surfers Ny", url: "subway-surfers-ny" },
  "suggestions": { title: "Suggestions", url: "suggestions" },
  "superautopets": { title: "Superautopets", url: "superautopets" },
  "superfowlist": { title: "Superfowlist", url: "superfowlist" },
  "superhot": { title: "Superhot", url: "superhot" },
  "supermarioconstruct": { title: "Super Mario Construct", url: "supermarioconstruct" },
  "surviv": { title: "Surviv", url: "surviv" },
  "sushi-unroll": { title: "Sushi Unroll", url: "sushi-unroll" },
  "swarmsimulator": { title: "Swarmsimulator", url: "swarmsimulator" },
  "swerve": { title: "Swerve", url: "swerve" },
  "synesthesia": { title: "Synesthesia", url: "synesthesia" },
  "tactical-weapon-pack-2": { title: "Tactical Weapon Pack 2", url: "tactical-weapon-pack-2" },
  "tacticalassasin2": { title: "Tacticalassasin2", url: "tacticalassasin2" },
  "tank-trouble-2": { title: "Tank Trouble 2", url: "tank-trouble-2" },
  "tanuki-sunset": { title: "Tanuki Sunset", url: "tanuki-sunset" },
  "temple-run-2": { title: "Temple Run 2", url: "temple-run-2" },
  "the-final-earth": { title: "The Final Earth", url: "the-final-earth" },
  "the-final-earth-2": { title: "The Final Earth 2", url: "the-final-earth-2" },
  "the-hotel": { title: "The Hotel", url: "the-hotel" },
  "thebattle": { title: "Thebattle", url: "thebattle" },
  "theheist": { title: "Theheist", url: "theheist" },
  "there-is-no-game": { title: "There Is No Game", url: "there-is-no-game" },
  "thisistheonlylevel": { title: "Thisistheonlylevel", url: "thisistheonlylevel" },
  "throwrocks": { title: "Throwrocks", url: "throwrocks" },
  "tiny-fishing": { title: "Tiny Fishing", url: "tiny-fishing" },
  "tiny-islands": { title: "Tiny Islands", url: "tiny-islands" },
  "tosstheturtle": { title: "Tosstheturtle", url: "tosstheturtle" },
  "townscaper": { title: "Townscaper", url: "townscaper" },
  "tube-jumpers": { title: "Tube Jumpers", url: "tube-jumpers" },
  "tunnel-rush": { title: "Tunnel Rush", url: "tunnel-rush" },
  "tv-static": { title: "Tv Static", url: "tv-static" },
  "twitch-tetris": { title: "Twitch Tetris", url: "twitch-tetris" },
  "unfairmario": { title: "Unfairmario", url: "unfairmario" },
  "veloce": { title: "Veloce", url: "veloce" },
  "vex2": { title: "Vex2", url: "vex2" },
  "vex3": { title: "Vex3", url: "vex3" },
  "vex4": { title: "Vex4", url: "vex4" },
  "vex5": { title: "Vex5", url: "vex5" },
  "vex6": { title: "Vex6", url: "vex6" },
  "vex7": { title: "Vex7", url: "vex7" },
  "volley-random": { title: "Volley Random", url: "volley-random" },
  "wallsmash": { title: "Wallsmash", url: "wallsmash" },
  "waterworks": { title: "Waterworks", url: "waterworks" },
  "weavesilk": { title: "Weavesilk", url: "weavesilk" },
  "webcleaner": { title: "Webcleaner", url: "webcleaner" },
  "webgl-fluid-simulation": { title: "Webgl Fluid Simulation", url: "webgl-fluid-simulation" },
  "webretro": { title: "Webretro", url: "webretro" },
  "webxash": { title: "Webxash", url: "webxash" },
  "win-the-whitehouse": { title: "Win The Whitehouse", url: "win-the-whitehouse" },
  "wolf2d": { title: "Wolf2d", url: "wolf2d" },
  "wolf3d": { title: "Wolf3d", url: "wolf3d" },
  "wordle": { title: "Wordle", url: "wordle" },
  "worlds-hardest-game": { title: "Worlds Hardest Game", url: "worlds-hardest-game" },
  "worlds-hardest-game-2": { title: "Worlds Hardest Game 2", url: "worlds-hardest-game-2" },
  "wounded-summer-baby-edition": { title: "Wounded Summer Baby Edition", url: "wounded-summer-baby-edition" },
  "x-trial-racing": { title: "X Trial Racing", url: "x-trial-racing" },
  "xx142-b2exe": { title: "Xx142 B2exe", url: "xx142-b2exe" },
  "yohoho": { title: "Yohoho", url: "yohoho" },
  "yoshifabrication": { title: "Yoshifabrication", url: "yoshifabrication" },
  "you-are-bezos": { title: "You Are Bezos", url: "you-are-bezos" },
  "zigzag": { title: "Zigzag", url: "zigzag" },
  "zombs-royale": { title: "Zombs Royale", url: "zombs-royale" }
};