const gameConfigs = {
  "10-minutes-till-dawn": { title: "10 Minutes Till Dawn", url: "10-minutes-till-dawn", icon: "fas fa-clock" },
  "2048": { title: "2048", url: "2048", icon: "fas fa-th" },
  "2048-multitask": { title: "2048 Multitask", url: "2048-multitask", icon: "fas fa-th" },
  "9007199254740992": { title: "9007199254740992", url: "9007199254740992", icon: "fas fa-th" },
  "a-dance-of-fire-and-ice": { title: "A Dance of Fire and Ice", url: "a-dance-of-fire-and-ice", icon: "fas fa-music" },
  "a-dark-room": { title: "A Dark Room", url: "a-dark-room", icon: "fas fa-fire" },
  "adrenaline-challenge": { title: "Adrenaline Challenge", url: "adrenaline-challenge", icon: "fas fa-bolt" },
  "adventure-drivers": { title: "Adventure Drivers", url: "adventure-drivers", icon: "fas fa-car" },
  "ages-of-conflict": { title: "Ages of Conflict", url: "ages-of-conflict", icon: "fas fa-globe" },
  "backrooms": { title: "Backrooms", url: "backrooms", icon: "fas fa-door-open" },
  "backrooms-2d": { title: "Backrooms 2D", url: "backrooms-2d", icon: "fas fa-door-closed" },
  "bacon-may-die": { title: "Bacon May Die", url: "bacon-may-die", icon: "fas fa-skull" },
  "bad-ice-cream": { title: "Bad Ice Cream", url: "bad-ice-cream", icon: "fas fa-ice-cream" },
  "bad-ice-cream-2": { title: "Bad Ice Cream 2", url: "bad-ice-cream-2", icon: "fas fa-ice-cream" },
  "bad-ice-cream-3": { title: "Bad Ice Cream 3", url: "bad-ice-cream-3", icon: "fas fa-ice-cream" },
  "baldis-basics": { title: "Baldi's Basics", url: "baldis-basics", icon: "fas fa-school" },
  "basket-random": { title: "Basket Random", url: "basket-random", icon: "fas fa-basketball-ball" },
  "bitlife": { title: "BitLife", url: "bitlife", icon: "fas fa-user" },
  "boxing-random": { title: "Boxing Random", url: "boxing-random", icon: "fas fa-fist-raised" },
  "btts": { title: "Big Tower Tiny Square", url: "btts", icon: "fas fa-building" },
  "buckshot-roulette": { title: "Buckshot Roulette", url: "buckshot-roulette", icon: "fas fa-gun" },
  "cluster-rush": { title: "Cluster Rush", url: "cluster-rush", icon: "fas fa-running" },
  "core-ball": { title: "Core Ball", url: "core-ball", icon: "fas fa-dot-circle" },
  "creative-kill-chamber": { title: "Creative Kill Chamber", url: "creative-kill-chamber", icon: "fas fa-skull-crossbones" },
  "crossy-road": { title: "Crossy Road", url: "crossy-road", icon: "fas fa-road" },
  "cupcake-2048": { title: "Cupcake 2048", url: "cupcake-2048", icon: "fas fa-birthday-cake" },
  "dante": { title: "Dante", url: "dante", icon: "fas fa-fire" },
  "deal-or-no-deal": { title: "Deal or No Deal", url: "deal-or-no-deal", icon: "fas fa-briefcase" },
  "death-run-3d": { title: "Death Run 3D", url: "death-run-3d", icon: "fas fa-skull-crossbones" },
  "drift-boss": { title: "Drift Boss", url: "drift-boss", icon: "fas fa-car" },
  "drift-hunters": { title: "Drift Hunters", url: "drift-hunters", icon: "fas fa-car-side" },
  "drive-mad": { title: "Drive Mad", url: "drive-mad", icon: "fas fa-car-crash" },
  "ducklife3": { title: "Duck Life 3", url: "duck-life-3", icon: "fas fa-duck" },
  "ducklife4": { title: "Duck Life 4", url: "duck-life-4", icon: "fas fa-duck" },
  "eggy-car": { title: "Eggy Car", url: "eggy-car", icon: "fas fa-egg" },
  "fnaw": { title: "Five Nights at Winston's", url: "fnaw", icon: "fas fa-ghost" },
  "funny-shooter": { title: "Funny Shooter", url: "funny-shooter", icon: "fas fa-gun" },
  "funny-shooter-2": { title: "Funny Shooter 2", url: "funny-shooter-2", icon: "fas fa-gun" },
  "getaway-shootout": { title: "Getaway Shootout", url: "getaway-shootout", icon: "fas fa-gun" },
  "learn-to-fly": { title: "Learn to Fly", url: "learn-to-fly", icon: "fas fa-dove" },
  "learn-to-fly-2": { title: "Learn to Fly 2", url: "learn-to-fly-2", icon: "fas fa-dove" },
  "madalin-stunt-cars-2": { title: "Madalin Stunt Cars 2", url: "madalin-stunt-cars-2", icon: "fas fa-car" },
  "madalin-stunt-cars-3": { title: "Madalin Stunt Cars 3", url: "madalin-stunt-cars-3", icon: "fas fa-car" },
  "monkey-mart": { title: "Monkey Mart", url: "monkey-mart", icon: "fas fa-apple-alt" },
  "motox3m": { title: "MotoX3M", url: "motox3m", icon: "fas fa-motorcycle" },
  "motox3m-pool": { title: "MotoX3M Pool Party", url: "motox3m-pool", icon: "fas fa-motorcycle" },
  "motox3m-spooky": { title: "MotoX3M Spooky Land", url: "motox3m-spooky", icon: "fas fa-motorcycle" },
  "motox3m-winter": { title: "MotoX3M Winter", url: "motox3m-winter", icon: "fas fa-motorcycle" },
  "motox3m-2": { title: "MotoX3M 2", url: "motox3m-2", icon: "fas fa-motorcycle" },
  "resent-client": { title: "Resent Client", url: "resent-client", icon: "fas fa-user" },
  "retro-bowl": { title: "Retro Bowl", url: "retro-bowl", icon: "fas fa-football-ball" },
  "rooftop-snipers": { title: "Rooftop Snipers", url: "rooftop-snipers", icon: "fas fa-crosshairs" },
  "run-3": { title: "Run 3", url: "run-3", icon: "fas fa-running" },
  "scrap-metal": { title: "Scrap Metal", url: "scrap-metal", icon: "fas fa-cog" },
  "slope": { title: "Slope", url: "slope", icon: "fas fa-chart-line" },
  "slope-2": { title: "Slope 2", url: "slope-2", icon: "fas fa-chart-line" },
  "slope-ball": { title: "Slope Ball", url: "slope-ball", icon: "fas fa-volleyball-ball" },
  "snow-rider-3d": { title: "Snow Rider 3D", url: "snow-rider-3d", icon: "fas fa-skiing" },
  "soccer-random": { title: "Soccer Random", url: "soccer-random", icon: "fas fa-futbol" },
  "stickman-hook": { title: "Stickman Hook", url: "stickman-hook", icon: "fas fa-anchor" },
  "super-hot": { title: "SUPERHOT", url: "super-hot", icon: "fas fa-fire" },
  "tanuki-sunset": { title: "Tanuki Sunset", url: "tanuki-sunset", icon: "fas fa-sun" },
  "tunnel-rush": { title: "Tunnel Rush", url: "tunnel-rush", icon: "fas fa-tunnel" },
  "ultrakill": { title: "Ultrakill", url: "ultrakill", icon: "fas fa-gun" },
  "vex-3": { title: "Vex 3", url: "vex-3", icon: "fas fa-running" },
  "vex-4": { title: "Vex 4", url: "vex-4", icon: "fas fa-running" },
  "vex-5": { title: "Vex 5", url: "vex-5", icon: "fas fa-running" },
  "vex-6": { title: "Vex 6", url: "vex-6", icon: "fas fa-running" },
  "vex-7": { title: "Vex 7", url: "vex-7", icon: "fas fa-running" },
  "volley-random": { title: "Volley Random", url: "volley-random", icon: "fas fa-volleyball-ball" },
  "worlds-hardest-game": { title: "World's Hardest Game", url: "worlds-hardest-game", icon: "fas fa-gamepad" },
  "worlds-hardest-game-2": { title: "World's Hardest Game 2", url: "worlds-hardest-game-2", icon: "fas fa-gamepad" }
};